language: android

jdk: oraclejdk8

branches:
  only:
    - master
    
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools
    # - tools

    # The BuildTools version used by your project
    - build-tools-22.0.1

    # The SDK version used to compile your project
    - android-22

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-22
    
script:
  - TERM=dumb ./gradlew clean assemble -PdisablePreDex

notifications:
  email: false
